import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import dns from 'dns'; 
dns.setServers(['8.8.8.8', '8.8.4.4']);

import {NuqsAdapter} from "nuqs/adapters/next/app";


import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const dmSans = DM_Sans({
  subsets:['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.className} antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
        <TRPCReactProvider>
        {children}
        <Toaster/>
        </TRPCReactProvider>
        </NuqsAdapter>
        </body>
    </html>
  );
}
